### ISSUE TITLE
Fix IIc+ drive issue

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#25]
See https://www.chebucto.ns.ca/Services/PDA/IIc+DrvStop.txt 

> Due to a bug in the firmware of the IIc+, internal and external drives continue running when using A2Desktop v1.1. 

We should try to build a workaround in.

**Comment by mgcaret** [comment]
Anything that makes a SmartPort status call to the IIc Plus slot 5 firmware causes a brief drive access.

The only reasonable way to fix this on a IIc Plus is to detect that we are running on one, and if so treat slot 5 as slot 6 ("Check Drives") or drastically decrease the polling frequency (which may still be annoying).

Another option would be to have a checkbox item such as "Poll drives" that would enable or disable all SmartPort polling (i.e. if selected, behave as it is, otherwise require "Check Drives" to be used for all drives).  On the IIc Plus, such a "Poll drives" option would default to off.

**Comment by mgcaret** [comment]
I will try to test tomorrow. 


--MG

**Comment by mgcaret** [comment]
Finally got to this, built master today, internal drive still goes constantly. 

Also, I found an anomaly with This Apple, it detects the memory incorrectly on my IIc Plus.  (The detected CPU is correct, 65802 in this one). 

Also, I got a Le Chat Mauve //c.  I am pleased to see desktop correctly configure it for monochrome. :-). 

MG

**Comment by inexorabletash** [comment]
Thanks for checking it out!

>  I am pleased to see desktop correctly configure it for monochrome.

Yeah, I was pleasantly surprised when I was trying a GS emulator and it "just worked" when viewing images and entering/exiting DeskTop. I don't think I have DeskTop _exiting_ monochrome for either Le Chat Mauve or AppleColor card at the moment.

**Comment by inexorabletash** [comment]
If you search on`is_iic_plus_flag` you might see where I have the logic wrong.

**Comment by mgcaret** [comment]
Ahh, I see the problem.  In detect_machine the usual bytes are checked at the beginning, the routine then switches in the language card, and after that it checks $FBBF -- with the LC still active and therefore reading the RAM, not the ROM.

**Comment by inexorabletash** [comment]
Thanks. Thought it'd be something dumb like that. 

Are you able to tweak it and verify the behavior?

**Comment by mgcaret** [comment]
I am getting things set up to do just that.

**Comment by inexorabletash** [comment]
Cool. I'll look at rewriting that code.

**Comment by inexorabletash** [comment]
Rewrote the code. Give it a whirl?

**Comment by mgcaret** [comment]
Your fix is better anyway.  Confirmed resolved.
